### ISSUE TITLE
Export More Than One Day?

### ISSUE THREAD

**Issue by ToAFinish** [abisek/salesforce-elf-browser#11]
Hi, thank you for a great tool!

Is there a way in the configuration to export more than one day?  Currently, we can only export a CSV for each day, but it would be massively helpful if we could export a whole month, say...

Thank you!

Joseph

**Comment by abisek** [comment]
I'm sorry, but I moved out of Event Monitoring team and the project isn't actively developed. 

You may want to use [Force CLI](https://force-cli.heroku.com/) for downloading the files. Look for the `eventlogfile` sub-command. Being a CLI application, you can easily develop scripts to download the files for the entire month.
