### ISSUE TITLE
1 month data download

### ISSUE THREAD

**Issue by sateeshvidiyala** [abisek/salesforce-elf-browser#13]
Hi there,

First of all, this is a great app. 
Issue : I need an option to download one month data ( Last 30 days) into as one file. Is there any possibility. let me know. thank you! 

Regards
Sateesh

**Comment by abisek** [comment]
Unfortunately, this is no longer actively developed. See this for alternate solutions: https://github.com/abisek/salesforce-elf-browser/issues/11
