### ISSUE TITLE
Extract file issue

### ISSUE THREAD

**Issue by elenacomunianatos** [abisek/salesforce-elf-browser#7]
Dear Heroku team,
I'm writing you here because there isn't any support contact and Application Issue doesn't work correctly...
I need some support for herokuapp extraction, could you please help us?
Salesforce team suggest us to use heroku.app for event monitoring of community, we simulated an user itinerary click and the day after we checked with heroku.app but we can see only some link in URI extraction,instead we have a detail itineray click on "Reffer", and we did't understand how we know that 
UITracking (mobile clicks) tracks mobile clicks..
thank you in advance

**Comment by amandagrady** [comment]
Have you purchased the Event Monitoring product as this is an add-on to the platform? If not reach out to your sales contact to request a trial. Here's a getting started guide & Trailhead for once you've done that:
http://www.salesforcehacker.com/2015/03/event-monitoring-quick-start-guide.html
https://trailhead.salesforce.com/en/module/event_monitoring

**Comment by elenacomunianatos** [comment]
No, at the moment we are testing this tool (below the link salesforce team suggested us) for our very important client who wants to monitor mobile and brower click on a community salesforce org. https://salesforce-elf.herokuapp.com/event_log_files?daterange=2017-01-11+to+2017-01-11&eventtype=All.
I have already contacted salesforce team and they answered that  https://salesforce-elf.herokuapp.com/event_log_files?daterange=2017-01-11+to+2017-01-11&eventtype=All. is relate only to Heroku support and they didn't know....
So I have already opened some issues to Heroku but they answered us they didn't know about heroku.app and to open a ticket in the bottom of the page "Report" as I have done...
I have already seen these the link you gave but in https://trailhead.salesforce.com/event_monitoring/event_monitoring_intro there is explained that UITracking (mobile clicks), We exctracted UITracking file and there is no information that shows the records come from mobile app..the browser is Google as for desktop navigation...
In the same doc URi should register user clicks but (we simulated a user itinerary) a lot of information are missing...and we didn't know why

Is there a support team or somebody who can support us?

thank you in advance

**Comment by amandagrady** [comment]
The ELF browser is simply a tool to view the Event Monitoring data, it won't work unless you have purchased or are trialling the Event Monitoring add-on. This is a supported feature so Salesforce technical support would be able to help once you have worked with your sales contact to purchase or trial. 

The feature is only for customers to monitoring their own data, there isn't a partner version to monitor their customers' data.
