### ISSUE TITLE
OAuth2 login failed. Reason: OAUTH_APP_ACCESS_DENIED

### ISSUE THREAD

**Issue by cdieter** [abisek/salesforce-elf-browser#9]
Hello - I have enabled event monitoring on one of our production environments, but I am getting the above error when trying to log into this tool. Are there any permission sets or system permissions I must enable to let this tool gain access to my org's data?

**Comment by abisek** [comment]
@cdieter My apologies for the late response as I no longer work for the team that owns this project. 

In case you are still looking for an answer or someone else stumbles upon this question, here are the reasons why you'd get the error:
1. User may have declined to grant the permission to the connected app.
2. Org's IP restriction on connected app.
